### ISSUE TITLE
GPT可能暂时不想理你时出现HTTP 401 Unauthorized

### ISSUE THREAD

**Issue by Anjuice666** [ashinnotfound/ChatGPT-QQRobot#16]
`retrofit2.adapter.rxjava2.HttpException: HTTP 401 Unauthorized
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:57) ~[adapter-rxjava2-2.9.0.jar:na]
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:38) ~[adapter-rxjava2-2.9.0.jar:na]
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48) ~[adapter-rxjava2-2.9.0.jar:na]
	at io.reactivex.Observable.subscribe(Observable.java:12284) ~[rxjava-2.2.21.jar:na]
	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35) ~[adapter-rxjava2-2.9.0.jar:na]
	at io.reactivex.Observable.subscribe(Observable.java:12284) ~[rxjava-2.2.21.jar:na]
	at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35) ~[rxjava-2.2.21.jar:na]
	at io.reactivex.Single.subscribe(Single.java:3666) ~[rxjava-2.2.21.jar:na]
	at io.reactivex.Single.blockingGet(Single.java:2869) ~[rxjava-2.2.21.jar:na]
	at com.theokanning.openai.OpenAiService.createCompletion(OpenAiService.java:116) ~[client-0.9.0.jar:na]
	at com.ashin.service.InteractServiceImpl.chat(InteractServiceImpl.java:33) ~[classes/:na]
	at com.ashin.controller.MessageEventHandler.response(MessageEventHandler.java:68) [classes/:na]
	at com.ashin.controller.MessageEventHandler.onMessage(MessageEventHandler.java:50) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt.registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:140) [mirai-core-api-jvm-2.13.4.jar:2.13.4]
	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt.access$registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:1) [mirai-core-api-jvm-2.13.4.jar:2.13.4]
	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt$registerEventHandler$callMethod$2.invokeSuspend(JvmMethodListenersInternal.kt:154) [mirai-core-api-jvm-2.13.4.jar:2.13.4]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.6.21.jar:1.6.21-release-334(1.6.21)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42) [kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95) [kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) [kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) [kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) [kotlinx-coroutines-core-jvm-1.6.4.jar:na]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) [kotlinx-coroutines-core-jvm-1.6.4.jar:na]
`

**Comment by ashinnotfound** [comment]
应该是apikey没配置正确，你往上看看初始化账号时打印的apikey信息是否正确

**Comment by Anjuice666** [comment]
> 应该是apikey没配置正确，你往上看看初始化账号时打印的apikey信息是否正确

apikey读取信息正确，显示账号初始化成功，也成功登陆qq

**Comment by ashinnotfound** [comment]
> 应该是有一个账号出了问题，去掉之后正常啦~> 应该是apikey没配置正确，你往上看看初始化账号时打印的apikey信息是否正确
> 
> apikey读取信息正确，显示账号初始化成功，也成功登陆qq

ok😀

**Comment by wb3368316006** [comment]
我的也出现这个问题，已确认 apikey配置正确
<img width="1281" alt="image" src="https://user-images.githubusercontent.com/89630969/218664129-b5981d91-c388-4d61-8456-8d0d7fa52e2c.png">重启后日志信息显示账号初始化成功，但是无法使用，一直是gpt不想理你

**Comment by lin666999** [comment]
去替换掉哪个token吗sk---------TH9f5VSwlsi
