### ISSUE TITLE
问了几个问题，然后就一直报错了

### ISSUE THREAD

**Issue by yuanbing1010** [ashinnotfound/ChatGPT-QQRobot#6]
报错内容如下：

2023-02-06 09:53:13 W/Bot 969948762: An exception occurred when processing event. Subscriber scope: '<unnamed>'. Broadcaster scope: 'Bot.969948762.EventDispatcher'
net.mamoe.mirai.event.ExceptionInEventHandlerException: Exception in EventHandler
	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt.registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:147)
	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt.access$registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:1)
	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt$registerEventHandler$callMethod$2.invokeSuspend(JvmMethodListenersInternal.kt:154)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.mamoe.mirai.internal.event.JvmMethodListenersInternalKt.registerEventHandler$callMethod$invokeWithErrorReport(JvmMethodListenersInternal.kt:140)
	... 10 more
Caused by: retrofit2.adapter.rxjava2.HttpException: HTTP 400 
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:57)
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:38)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
	at io.reactivex.Observable.subscribe(Observable.java:12284)
	at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
	at io.reactivex.Single.subscribe(Single.java:3666)
	at io.reactivex.Single.blockingGet(Single.java:2869)
	at com.theokanning.openai.OpenAiService.createCompletion(OpenAiService.java:116)
	at com.ashin.service.InteractServiceImpl.chat(InteractServiceImpl.java:26)
	at com.ashin.controller.MessageEventHandler.onMessage(MessageEventHandler.java:52)
	... 14 more

求大神看看能不能解决，感谢！

**Comment by yuanbing1010** [comment]
感谢大佬回复和看问题，比心



---原始邮件---
发件人: "xun ***@***.***&gt;
发送时间: 2023年2月6日(周一) 上午10:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ashinnotfound/ChatGPT-QQRobot] 问了几个问题，然后就一直报错了 (Issue #6)




 
我尝试复现一下，感觉像是我的锅🫣

**Comment by ashinnotfound** [comment]
应该是解决了，你再试试

**Comment by ashinnotfound** [comment]
噢并没有解决，但我找到原因了，正在想解决方案

**Comment by yuanbing1010** [comment]
好的，谢谢，解决不了也暂时没什么大碍，属于偶发的bug，昨天部署到服务器上，到现在还能正常用



---原始邮件---
发件人: "xun ***@***.***&gt;
发送时间: 2023年2月6日(周一) 晚上8:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ashinnotfound/ChatGPT-QQRobot] 问了几个问题，然后就一直报错了 (Issue #6)




 
噢并没有解决，但我找到原因了，正在想解决方案
